// =====================================================================
//  SOUND — the desktop's voice, synthesised rather than sampled.
//
//  Every one of these is generated by oscillators and filtered noise at
//  run time. Two reasons, and the second is the real one:
//
//   1. There are no audio files to download. The site is still plain
//      modules with no dependencies, and a folder of .wav files would
//      be the heaviest thing on it by an order of magnitude.
//
//   2. Microsoft's actual sounds — TADA.WAV, the startup chime, the
//      Windows ding — are copyrighted, and shipping them on a public
//      site because they feel nostalgic is still copying them. These
//      are written in the same idiom: short, bright, unmistakably a
//      computer from that era, and entirely original.
//
//  Nothing here can make a sound before the visitor has clicked
//  something. That is partly the browser's autoplay policy and partly
//  good manners: a portfolio that starts talking to a recruiter in an
//  open-plan office is a portfolio they close.
// =====================================================================

const STORAGE_KEY = "ram.sound";

let ctx = null;
let master = null;

//  Someone who has asked their system for less motion has told you
//  something about how they want a web page to treat them. Default them
//  to silence — the tray toggle is still there if they want it.
const reduceMotion =
  typeof matchMedia === "function" &&
  matchMedia("(prefers-reduced-motion: reduce)").matches;

function stored() {
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    return v === null ? null : v === "on";
  } catch (err) {
    return null;                    // private mode, or storage disabled
  }
}

let on = stored();
if (on === null) on = !reduceMotion;

const volume = 0.25;
const listeners = [];

/*  Built on the first sound, never on load: constructing an
    AudioContext before a gesture leaves it suspended in most browsers,
    and some hold it against the page. */
function audio() {
  if (!ctx) {
    const Ctor = window.AudioContext || window.webkitAudioContext;
    if (!Ctor) return null;
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = volume;
    master.connect(ctx.destination);
  }
  if (ctx.state === "suspended") ctx.resume();
  return ctx;
}

/*  One oscillator with an envelope. `to` bends the pitch across the life
    of the note, which is most of what makes these read as an interface
    rather than as music. */
function tone(o) {
  const c = audio();
  if (!c) return;
  const t0 = c.currentTime + (o.delay || 0);
  const dur = o.dur || 0.08;

  const osc = c.createOscillator();
  osc.type = o.type || "square";
  osc.frequency.setValueAtTime(o.freq, t0);
  if (o.to) osc.frequency.exponentialRampToValueAtTime(o.to, t0 + dur);

  const gain = c.createGain();
  const peak = o.gain === undefined ? 0.5 : o.gain;
  //  Ramps, never a bare setValue: a gain that jumps from nothing to
  //  full in one sample is itself a click, and you hear it on every note.
  gain.gain.setValueAtTime(0.0001, t0);
  gain.gain.exponentialRampToValueAtTime(peak, t0 + Math.min(0.012, dur / 3));
  gain.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  osc.connect(gain);
  gain.connect(master);
  osc.start(t0);
  osc.stop(t0 + dur + 0.02);
}

/*  A burst of noise through a filter. Every mechanical sound here — the
    tick of a click, the rush of the warp — is this. */
function noise(o) {
  const c = audio();
  if (!c) return;
  const t0 = c.currentTime + (o.delay || 0);
  const dur = o.dur || 0.06;

  const frames = Math.max(1, Math.floor(c.sampleRate * dur));
  const buffer = c.createBuffer(1, frames, c.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) data[i] = Math.random() * 2 - 1;

  const src = c.createBufferSource();
  src.buffer = buffer;

  const filter = c.createBiquadFilter();
  filter.type = o.type || "bandpass";
  filter.frequency.setValueAtTime(o.freq || 2000, t0);
  if (o.to) filter.frequency.exponentialRampToValueAtTime(o.to, t0 + dur);
  filter.Q.value = o.q === undefined ? 1 : o.q;

  const gain = c.createGain();
  const peak = o.gain === undefined ? 0.3 : o.gain;
  gain.gain.setValueAtTime(0.0001, t0);
  gain.gain.exponentialRampToValueAtTime(peak, t0 + Math.min(0.02, dur / 3));
  gain.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  src.connect(filter);
  filter.connect(gain);
  gain.connect(master);
  src.start(t0);
  src.stop(t0 + dur + 0.02);
}

// ------------------------------------------------------------- voices
//  Kept short. An interface sound that outlasts the action it describes
//  stops being feedback and becomes an opinion.
const VOICES = {
  //  The one long sound on the site: a major add-nine spread over a
  //  second, each voice entering underneath the one before it.
  startup: function () {
    [[392, 0], [523.25, 0.12], [659.25, 0.24], [880, 0.36]]
      .forEach(function (n) {
        tone({ freq: n[0], type: "triangle", delay: n[1], dur: 1.1, gain: 0.16 });
      });
    tone({ freq: 196, type: "sine", dur: 1.4, gain: 0.12 });
  },

  open:     function () { tone({ freq: 520, to: 880, type: "square",   dur: 0.07, gain: 0.16 }); },
  close:    function () { tone({ freq: 660, to: 300, type: "square",   dur: 0.09, gain: 0.16 }); },
  minimise: function () { tone({ freq: 700, to: 260, type: "triangle", dur: 0.11, gain: 0.14 }); },
  maximise: function () { tone({ freq: 320, to: 720, type: "triangle", dur: 0.11, gain: 0.14 }); },

  //  The workhorse: thirty-five milliseconds of filtered noise.
  //  Anything longer becomes exhausting by the tenth click.
  click: function () { noise({ freq: 2600, to: 1400, dur: 0.035, gain: 0.16, q: 0.8 }); },
  menu:  function () { noise({ freq: 1800, to: 3000, dur: 0.045, gain: 0.14, q: 0.9 }); },

  //  Two flat low notes, deliberately unmusical. An error that sounds
  //  pleasant is an error nobody attends to.
  error: function () {
    tone({ freq: 220, type: "square", dur: 0.12, gain: 0.18 });
    tone({ freq: 208, type: "square", dur: 0.16, gain: 0.18, delay: 0.14 });
  },

  //  The mascot clearing its throat, and an answer landing.
  notify: function () {
    tone({ freq: 880,  type: "sine", dur: 0.09, gain: 0.14 });
    tone({ freq: 1318, type: "sine", dur: 0.14, gain: 0.12, delay: 0.09 });
  },

  //  Twenty years of travel in a second and a half: a filter sweep
  //  climbing through noise, the pitch pulling up underneath it, and a
  //  single bright note as you land.
  warp: function () {
    noise({ freq: 200, to: 6000, dur: 1.5, gain: 0.2, type: "lowpass", q: 6 });
    tone({ freq: 110, to: 1200, type: "sawtooth", dur: 1.5, gain: 0.08 });
    tone({ freq: 1600, type: "sine", dur: 0.5, gain: 0.1, delay: 1.3 });
  }
};

// ---------------------------------------------------------------- API
export const sound = {
  get enabled() { return on; },

  set enabled(v) {
    on = !!v;
    try { localStorage.setItem(STORAGE_KEY, on ? "on" : "off"); } catch (err) {}
    if (on) audio();                  // resume while the click is still live
    listeners.forEach(function (fn) { fn(on); });
  },

  toggle: function () { sound.enabled = !on; return on; },

  onChange: function (fn) { listeners.push(fn); fn(on); },

  /*  Called from the first real gesture. Browsers will not start an
      AudioContext outside one, so without this the first sound of a
      session is silently dropped. */
  unlock: function () { if (on) audio(); },

  play: function (name) {
    if (!on) return;
    const voice = VOICES[name];
    if (!voice) return;
    //  A failure here means a blocked context or a missing API, never
    //  anything worth interrupting the page for.
    try { voice(); } catch (err) {}
  }
};
